#!/usr/bin/env bun
/**
 * Compile a self-contained `aurora` CLI binary that embeds the Docker build
 * context (same files `docker build .` would send, honoring `.dockerignore`).
 *
 * At runtime the binary feeds that tar to `docker build -` on stdin — Docker
 * on the host is still required; the repo tree is not.
 *
 *   bun run aurora.bun.build.ts
 *   AURORA_CLI_TARGET=bun-windows-x64 AURORA_CLI_OUT=aurora-windows-x64 bun run build:cli
 *   ./aurora
 */

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { listContextFiles, missingRequired, parseDockerIgnore } from './cli/docker-context';

const ROOT = resolve(import.meta.dir);
const EMBED_DIR = join(ROOT, 'cli', '.embedded');
const CONTEXT_TAR = join(EMBED_DIR, 'docker-context.tar');
const EMBEDDED_CONTEXT_TS = join(ROOT, 'cli', 'embedded-context.ts');
const OUTFILE = resolve(ROOT, Bun.env.AURORA_CLI_OUT ?? 'aurora');
/** Bun cross-compile target, e.g. `bun-darwin-arm64`, `bun-windows-x64`. */
const COMPILE_TARGET = (Bun.env.AURORA_CLI_TARGET?.trim() || undefined) as
  | Bun.Build.CompileTarget
  | undefined;

const EMBEDDED_CONTEXT_STUB = `/** Stub for source runs — \`aurora.bun.build.ts\` swaps in an embedded import before compile. */
export const EMBEDDED_DOCKER_CONTEXT_PATH: string | null = null;
`;

const EMBEDDED_CONTEXT_RELEASE = `/** Generated by aurora.bun.build.ts — embeds the Docker build-context tar. */
import dockerContextTar from "./.embedded/docker-context.tar" with { type: "file" };
export const EMBEDDED_DOCKER_CONTEXT_PATH: string | null = dockerContextTar;
`;

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KiB`;
  if (n < 1024 ** 3) return `${(n / 1024 ** 2).toFixed(1)} MiB`;
  return `${(n / 1024 ** 3).toFixed(2)} GiB`;
}

async function writeContextTar(files: string[], outTar: string): Promise<void> {
  mkdirSync(EMBED_DIR, { recursive: true });
  const staging = mkdtempSync(join(tmpdir(), 'aurora-context-'));
  const listFile = join(staging, 'files.txt');
  try {
    writeFileSync(listFile, `${files.join('\n')}\n`);
    const proc = Bun.spawnSync(['tar', '-cf', outTar, '-C', ROOT, '-T', listFile], {
      stdout: 'inherit',
      stderr: 'inherit',
    });
    if (proc.exitCode !== 0) {
      throw new Error(`tar failed with exit ${proc.exitCode}`);
    }
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

console.log('[build] assembling Docker build context (honors .dockerignore)…');
const dockerignoreText = await Bun.file(join(ROOT, '.dockerignore')).text();
const rules = parseDockerIgnore(dockerignoreText);
const files = listContextFiles(ROOT, rules);
if (files.length === 0) {
  console.error('[build] no files matched for Docker context');
  process.exit(1);
}

const missing = missingRequired(files);
if (missing.length > 0) {
  console.error(`[build] context missing Dockerfile inputs: ${missing.join(', ')}`);
  process.exit(1);
}

await writeContextTar(files, CONTEXT_TAR);
const tarSize = (await Bun.file(CONTEXT_TAR).stat()).size;
console.log(
  `[build] wrote ${relative(ROOT, CONTEXT_TAR)} (${files.length} files, ${formatBytes(tarSize)})`,
);

writeFileSync(EMBEDDED_CONTEXT_TS, EMBEDDED_CONTEXT_RELEASE);

try {
  const targetNote = COMPILE_TARGET ? ` target=${COMPILE_TARGET}` : '';
  console.log(`[build] compiling ${OUTFILE}${targetNote} with embedded context…`);
  const result = await Bun.build({
    entrypoints: ['./cli/aurora.ts'],
    compile: {
      outfile: OUTFILE,
      ...(COMPILE_TARGET ? { target: COMPILE_TARGET } : {}),
    },
  });

  if (!result.success) {
    console.error('[build] Bun.build failed:');
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }
} finally {
  writeFileSync(EMBEDDED_CONTEXT_TS, EMBEDDED_CONTEXT_STUB);
}

// Windows cross-compiles append `.exe` when the outfile has no extension.
const builtPath = (await Bun.file(OUTFILE).exists()) ? OUTFILE : `${OUTFILE}.exe`;
const binSize = (await Bun.file(builtPath).stat()).size;
console.log(`[build] ok — ${builtPath} (${formatBytes(binSize)})`);
console.log('[build] Docker required on the host at runtime');
