project_name = "aurora"

geodynamo-url = "https://geodynamo.seemueller.workers.dev/"

[test]
command = ["sh", "-c", "bun install && bun run test"]
format_command = ["sh", "-c", "bun install && bun run format"]

#[security_scan]
#paths = [
## todo
#]

[agent_models]
claude  = "claude-opus-4-8"
