project_name = "bevy-osc-app"

[test]
command = ["sh", "-c", "bun install && bun run test"]
format_command = ["sh", "-c", "bun install && bun run format"]

#[security_scan]
#paths = [
## todo
#]

geodynamo-url = "https://geoffsee.github.io/geodynamo/"

[agent_models]
claude  = "claude-opus-4-8"
