project_name = "bevy-osc-app"

[test]
command = ["bun install && bun run test"]
format_command = ["bun install && bun run format"]

#[security_scan]
#paths = [
## todo
#]

[agent_models]
claude  = "claude-opus-4-8"
