import type { CuePreset } from "./types.ts";

export const cuePresets: Record<string, CuePreset> = {
	warmup: {
		crossfade: 0.5,
		intensity: 0.62,
		feedback: 0.22,
		depth: 0.15,
		palette: 0.58,
		deckAMode: 4,
		deckBMode: 4,
	},
	drop: {
		crossfade: 1,
		intensity: 1.25,
		feedback: 0.42,
		depth: 0.58,
		palette: 0.9,
		deckAMode: 2,
		deckBMode: 2,
	},
	tunnel: {
		crossfade: 0.25,
		intensity: 1.0,
		feedback: 0.5,
		depth: 0.85,
		palette: 0.66,
		deckAMode: 1,
		deckBMode: 3,
	},
	burst: {
		crossfade: 0.75,
		intensity: 1.35,
		feedback: 0.32,
		depth: 0.35,
		palette: 0.04,
		deckAMode: 2,
		deckBMode: 2,
	},
	wash: {
		crossfade: 0.5,
		intensity: 0.48,
		feedback: 0.68,
		depth: 0.25,
		palette: 0.33,
		deckAMode: 4,
		deckBMode: 4,
	},
	panic: {
		crossfade: 0.5,
		intensity: 0.22,
		feedback: 0.08,
		depth: 0,
		palette: 0.62,
		deckAMode: 4,
		deckBMode: 4,
		maxBrightness: 0.35,
		strobe: false,
		strobeLockout: true,
	},
};
